// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaRpE9ln9OcW6fvIgqNQRthiAbwYeso5Q',
    appId: '1:823625903410:android:7e4ca747e34825daeefb2b',
    messagingSenderId: '823625903410',
    projectId: 'a-chat-db3ab',
    storageBucket: 'a-chat-db3ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8dC8fEz8d9gH2w0D1KF79hYi3GdOKeWA',
    appId: '1:823625903410:ios:02b9d36aa77dbc4feefb2b',
    messagingSenderId: '823625903410',
    projectId: 'a-chat-db3ab',
    storageBucket: 'a-chat-db3ab.appspot.com',
    androidClientId: '823625903410-ei6jv31u48l59akqs7mj4tt50bobekr0.apps.googleusercontent.com',
    iosClientId: '823625903410-01lstd804sfko85pv6vsrj66fmptievi.apps.googleusercontent.com',
    iosBundleId: 'com.example.aChat',
  );
}
